package pl.marcinmilkowski.word_sketch.api;

import pl.marcinmilkowski.word_sketch.api.model.*;

import java.util.List;

/**
 * Utility class for serialising API response objects to CSV and XML export formats.
 *
 * <p>All methods accept an optional {@code limit} that caps the number of data rows written;
 * a value of {@code 0} (or negative) means no limit and all rows are included.</p>
 *
 * <p>No external library is required: CSV is generated by simple string concatenation with
 * RFC 4180 quoting; XML is generated as well-formed UTF-8 text with attribute escaping.</p>
 */
final class ExportUtils {

    private ExportUtils() {}

    // ── Sketch export ─────────────────────────────────────────────────────────

    /**
     * Converts a {@link SketchResponse} to CSV with columns:
     * {@code relation, lemma, collocate, pos, frequency, log_dice}.
     */
    static String sketchToCsv(SketchResponse response, int limit) {
        StringBuilder sb = new StringBuilder();
        sb.append("relation,lemma,collocate,pos,frequency,log_dice\n");
        if (response.relations() == null) return sb.toString();
        for (var entry : response.relations().entrySet()) {
            String relation = csvEscape(entry.getKey());
            String lemma = csvEscape(response.lemma());
            RelationEntry rel = entry.getValue();
            if (rel.collocations() == null) continue;
            int count = 0;
            for (CollocateEntry c : rel.collocations()) {
                if (isLimitExceeded(limit, count)) break;
                sb.append(relation).append(',')
                  .append(lemma).append(',')
                  .append(csvEscape(c.lemma())).append(',')
                  .append(csvEscape(c.pos())).append(',')
                  .append(c.frequency()).append(',')
                  .append(c.logDice()).append('\n');
                count++;
            }
        }
        return sb.toString();
    }

    /**
     * Converts a {@link SketchResponse} to XML.
     * Root element: {@code <sketch lemma="...">} with nested {@code <relation>}
     * and {@code <collocate>} elements.
     */
    static String sketchToXml(SketchResponse response, int limit) {
        StringBuilder sb = new StringBuilder();
        appendXmlHeader(sb);
        sb.append("<sketch lemma=\"").append(xmlAttr(response.lemma())).append("\">\n");
        if (response.relations() != null) {
            for (var entry : response.relations().entrySet()) {
                RelationEntry rel = entry.getValue();
                sb.append("  <relation id=\"").append(xmlAttr(entry.getKey())).append('"');
                if (rel.name() != null) sb.append(" name=\"").append(xmlAttr(rel.name())).append('"');
                sb.append(">\n");
                if (rel.collocations() != null) {
                    int count = 0;
                    for (CollocateEntry c : rel.collocations()) {
                        if (isLimitExceeded(limit, count)) break;
                        sb.append("    <collocate lemma=\"").append(xmlAttr(c.lemma())).append('"')
                          .append(" pos=\"").append(xmlAttr(c.pos())).append('"')
                          .append(" frequency=\"").append(c.frequency()).append('"')
                          .append(" log_dice=\"").append(c.logDice()).append('"')
                          .append("/>\n");
                        count++;
                    }
                }
                sb.append("  </relation>\n");
            }
        }
        sb.append("</sketch>\n");
        return sb.toString();
    }

    // ── Examples / concordance export ─────────────────────────────────────────

    /**
     * Converts an {@link ExamplesResponse} to CSV with columns:
     * {@code seed, collocate, relation, sentence}.
     */
    static String examplesToCsv(ExamplesResponse response, int limit) {
        StringBuilder sb = new StringBuilder();
        sb.append("seed,collocate,relation,sentence\n");
        String seed = csvEscape(response.seed());
        String collocate = csvEscape(response.collocate());
        String relation = csvEscape(response.relation());
        if (response.examples() == null) return sb.toString();
        int count = 0;
        for (ExampleEntry e : response.examples()) {
            if (isLimitExceeded(limit, count)) break;
            sb.append(seed).append(',')
              .append(collocate).append(',')
              .append(relation).append(',')
              .append(csvEscape(e.sentence())).append('\n');
            count++;
        }
        return sb.toString();
    }

    /**
     * Converts an {@link ExamplesResponse} to XML.
     * Root element: {@code <concordance seed="..." collocate="..." relation="...">}
     * with nested {@code <example>} CDATA sections.
     */
    static String examplesToXml(ExamplesResponse response, int limit) {
        StringBuilder sb = new StringBuilder();
        appendXmlHeader(sb);
        sb.append("<concordance")
          .append(" seed=\"").append(xmlAttr(response.seed())).append('"')
          .append(" collocate=\"").append(xmlAttr(response.collocate())).append('"')
          .append(" relation=\"").append(xmlAttr(response.relation())).append('"')
          .append(">\n");
        if (response.examples() != null) {
            int count = 0;
            for (ExampleEntry e : response.examples()) {
                if (isLimitExceeded(limit, count)) break;
                String sentence = e.sentence();
                if (sentence != null) {
                    // Ensure CDATA terminator does not appear inside the CDATA section
                    sentence = sentence.replace("]]>", "]]]]><![CDATA[>");
                }
                sb.append("  <example><![CDATA[").append(sentence).append("]]></example>\n");
                count++;
            }
        }
        sb.append("</concordance>\n");
        return sb.toString();
    }

    // ── Exploration export ────────────────────────────────────────────────────

    /**
     * Converts an {@link ExploreResponse} to CSV.
     * Emits two sections: {@code seed_collocates} (type=seed_collocate) and
     * {@code core_collocates} (type=core_collocate).
     * Columns: {@code type, word, log_dice, frequency_or_shared_by_count}.
     */
    static String exploreToCsv(ExploreResponse response, int limit) {
        StringBuilder sb = new StringBuilder();
        sb.append("type,word,log_dice,frequency_or_shared_by_count\n");
        if (response.seedCollocates() != null) {
            int count = 0;
            for (SeedCollocateEntry e : response.seedCollocates()) {
                if (isLimitExceeded(limit, count)) break;
                sb.append("seed_collocate,")
                  .append(csvEscape(e.word())).append(',')
                  .append(e.logDice()).append(',')
                  .append(e.frequency()).append('\n');
                count++;
            }
        }
        if (response.coreCollocates() != null) {
            int count = 0;
            for (CoreCollocateEntry e : response.coreCollocates()) {
                if (isLimitExceeded(limit, count)) break;
                sb.append("core_collocate,")
                  .append(csvEscape(e.word())).append(',')
                  .append(e.seedLogDice()).append(',')
                  .append(e.sharedByCount()).append('\n');
                count++;
            }
        }
        return sb.toString();
    }

    /**
     * Converts an {@link ExploreResponse} to XML.
     * Root element: {@code <exploration seed="...">} with nested
     * {@code <seed_collocates>} and {@code <core_collocates>} sections.
     */
    static String exploreToXml(ExploreResponse response, int limit) {
        StringBuilder sb = new StringBuilder();
        appendXmlHeader(sb);
        String seed = switch (response) {
            case ExploreResponse.SingleSeed s -> s.seed();
            case ExploreResponse.MultiSeed m -> String.join(",", m.seeds());
        };
        sb.append("<exploration seed=\"").append(xmlAttr(seed)).append("\">\n");

        sb.append("  <seed_collocates>\n");
        if (response.seedCollocates() != null) {
            int count = 0;
            for (SeedCollocateEntry e : response.seedCollocates()) {
                if (isLimitExceeded(limit, count)) break;
                sb.append("    <collocate word=\"").append(xmlAttr(e.word())).append('"')
                  .append(" log_dice=\"").append(e.logDice()).append('"')
                  .append(" frequency=\"").append(e.frequency()).append('"')
                  .append("/>\n");
                count++;
            }
        }
        sb.append("  </seed_collocates>\n");

        sb.append("  <core_collocates>\n");
        if (response.coreCollocates() != null) {
            int count = 0;
            for (CoreCollocateEntry e : response.coreCollocates()) {
                if (isLimitExceeded(limit, count)) break;
                sb.append("    <collocate word=\"").append(xmlAttr(e.word())).append('"')
                  .append(" shared_by_count=\"").append(e.sharedByCount()).append('"')
                  .append(" coverage=\"").append(e.coverage()).append('"')
                  .append("/>\n");
                count++;
            }
        }
        sb.append("  </core_collocates>\n");
        sb.append("</exploration>\n");
        return sb.toString();
    }

    // ── Comparison export ─────────────────────────────────────────────────────

    /**
     * Converts a {@link ComparisonResponse} to CSV with columns:
     * {@code word, category, present_in, total_nouns, avg_logdice, coverage}.
     */
    static String comparisonToCsv(ComparisonResponse response, int limit) {
        StringBuilder sb = new StringBuilder();
        sb.append("word,category,present_in,total_nouns,avg_logdice,coverage\n");
        if (response.collocates() == null) return sb.toString();
        int count = 0;
        for (CollocateProfileEntry e : response.collocates()) {
            if (isLimitExceeded(limit, count)) break;
            sb.append(csvEscape(e.word())).append(',')
              .append(csvEscape(e.category())).append(',')
              .append(e.presentIn()).append(',')
              .append(e.totalNouns()).append(',')
              .append(e.avgLogDice()).append(',')
              .append(e.commonalityScore()).append('\n');
            count++;
        }
        return sb.toString();
    }

    /**
     * Converts a {@link ComparisonResponse} to XML.
     * Root element: {@code <comparison seeds="...">} with nested {@code <collocate>} elements.
     */
    static String comparisonToXml(ComparisonResponse response, int limit) {
        StringBuilder sb = new StringBuilder();
        appendXmlHeader(sb);
        String seedsStr = response.seeds() != null ? String.join(",", response.seeds()) : "";
        sb.append("<comparison seeds=\"").append(xmlAttr(seedsStr)).append("\">\n");
        if (response.collocates() != null) {
            int count = 0;
            for (CollocateProfileEntry e : response.collocates()) {
                if (isLimitExceeded(limit, count)) break;
                sb.append("  <collocate word=\"").append(xmlAttr(e.word())).append('"')
                  .append(" category=\"").append(xmlAttr(e.category())).append('"')
                  .append(" present_in=\"").append(e.presentIn()).append('"')
                  .append(" total_nouns=\"").append(e.totalNouns()).append('"')
                  .append(" avg_logdice=\"").append(e.avgLogDice()).append('"')
                  .append(" coverage=\"").append(e.commonalityScore()).append('"')
                  .append("/>\n");
                count++;
            }
        }
        sb.append("</comparison>\n");
        return sb.toString();
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    /**
     * Returns {@code true} when a positive limit has been set and {@code count} has
     * reached or exceeded it.  A limit of {@code 0} or negative means "no limit".
     */
    static boolean isLimitExceeded(int limit, int count) {
        return limit > 0 && count >= limit;
    }

    /**
     * Escapes a value for RFC 4180 CSV inclusion.
     * If the value contains a comma, double-quote, newline, or carriage-return it is
     * wrapped in double-quotes and internal double-quotes are doubled.
     */
    static String csvEscape(String value) {
        if (value == null) return "";
        if (value.contains(",") || value.contains("\"")
                || value.contains("\n") || value.contains("\r")) {
            return "\"" + value.replace("\"", "\"\"") + "\"";
        }
        return value;
    }

    /**
     * Escapes a value for use as an XML attribute value (double-quoted).
     * Replaces {@code &}, {@code "}, {@code <}, and {@code >} with XML entities.
     */
    static String xmlAttr(String value) {
        if (value == null) return "";
        return value.replace("&", "&amp;")
                    .replace("\"", "&quot;")
                    .replace("<", "&lt;")
                    .replace(">", "&gt;");
    }

    private static void appendXmlHeader(StringBuilder sb) {
        sb.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
    }

    /**
     * Parses and validates the {@code format} query parameter.
     * Returns {@code "json"}, {@code "csv"}, or {@code "xml"}.
     *
     * @throws IllegalArgumentException if the value is present but not one of the allowed values
     */
    static String parseFormat(java.util.Map<String, String> params) {
        String raw = params.get("format");
        if (raw == null || raw.isBlank()) return "json";
        return switch (raw.trim().toLowerCase(java.util.Locale.ROOT)) {
            case "json" -> "json";
            case "csv" -> "csv";
            case "xml" -> "xml";
            default -> throw new IllegalArgumentException(
                "Invalid format parameter: '" + raw + "' (expected json, csv, or xml)");
        };
    }

    /**
     * Parses the {@code export_limit} query parameter.
     * Returns the specified non-negative integer, or {@code 0} (meaning no limit) when absent.
     *
     * @throws IllegalArgumentException if the value is not a valid non-negative integer
     */
    static int parseExportLimit(java.util.Map<String, String> params) {
        String raw = params.get("export_limit");
        if (raw == null) return 0;
        try {
            int v = Integer.parseInt(raw.trim());
            if (v < 0) {
                throw new IllegalArgumentException(
                    "Invalid export_limit: '" + raw + "' (must be a non-negative integer)");
            }
            return v;
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException(
                "Invalid export_limit: '" + raw + "' (expected non-negative integer)");
        }
    }

    /**
     * Returns a suggested download filename for the given lemma/context and format.
     *
     * @param context a short string describing the export (e.g. {@code "theory-sketch"})
     * @param format  {@code "csv"} or {@code "xml"}
     */
    static String downloadFilename(String context, String format) {
        String safe = context.replaceAll("[^A-Za-z0-9_\\-]", "_");
        return safe + "." + format;
    }
}
